# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
    workflow_dispatch:
#push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

#permissions:
#  contents: read

jobs:
#  build:
  automation:
    name: 自動化        
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install chromedriver_autoinstaller
        pip install httpx
    - name: SignIN
      run: |
        python ./main.py
        python ./lottery.py
      env:
        UID: ${{ secrets.UID }}
        PASSWD: ${{ secrets.PASSWD }}
